#ifndef _ACKNEXT_ACKDEF_H_
#define _ACKNEXT_ACKDEF_H_

#define ISOMETRIC (1<<0)
#define CLEAR_DEPTH (1<<0)
#define CLEAR_COLOR (1<<1)
#define CLEAR_STENCIL (1<<2)
#define FULLSCREEN (1<<0)
#define VISIBLE (1<<1)

#define CLEAR_TARGET (CLEAR_COLOR | CLEAR_DEPTH | CLEAR_STENCIL)

#endif // _ACKNEXT_ACKDEF_H_
