#ifndef _ACKNEXT_ACKENUM_H_
#define _ACKNEXT_ACKENUM_H_

typedef enum CAMERATYPE {
	PERSPECTIVE,
	ISOMETRIC,
	CUSTOM_PROJECTION,
} CAMERATYPE;

typedef enum ERROR {
	ERR_NOERROR,
	ERR_OUTOFMEMORY,
	ERR_INVALIDARGUMENT,
	ERR_INVALIDOPERATION,
	ERR_SDL,
	ERR_OUTOFBOUNDS,
	ERR_FILESYSTEM,
} ERROR;

typedef enum STAGETYPE {
	ENTITY_STAGE,
	POSTPROCESSING_STAGE,
	CUSTOM_STAGE,
} STAGETYPE;

typedef enum TASKSTATE {
	TASK_DEAD,
	TASK_READY,
	TASK_SUSPENDED,
	TASK_DISABLED,
	TASK_RUNNING,
} TASKSTATE;


#endif // _ACKNEXT_ACKDEF_H_
