#ifndef _ACKNEXT_ACKENUM_H_
#define _ACKNEXT_ACKENUM_H_

typedef enum CAMERATYPE {
	PERSPECTIVE,
	ISOMETRIC,
	CUSTOM_PROJECTION,
} CAMERATYPE;

typedef enum ERROR {
	ERR_NOERROR,
	ERR_OUTOFMEMORY,
	ERR_INVALIDARGUMENT,
	ERR_INVALIDOPERATION,
	ERR_SDL,
	ERR_OUTOFBOUNDS,
	ERR_FILESYSTEM,
} ERROR;

typedef enum HULLTYPE {
	HULL_SPHERE,
	HULL_BOX,
	HULL_CYLINDER,
	HULL_CAPSULE,
	HULL_POLYGON,
	HULL_CONVEX,
} HULLTYPE;

typedef enum SHADERVAR {
	MATWORLD_VAR = 1,
	MATVIEW_VAR = 2,
	MATPROJ_VAR = 3,
	MATWORLDVIEW_VAR = 4,
	MATVIEWPROJ_VAR = 5,
	MATWORLDVIEWPROJ_VAR = 6,
	VECVIEWDIR_VAR = 7,
	VECVIEWPOS_VAR = 8,
	VECVIEWPORT_VAR = 9,
	FARC_VAR = 10,
	VECALBEDO_VAR = 11,
	VECEMISSION_VAR = 12,
	VECATTRIBUTES_VAR = 13,
	TEXCOLOR_VAR = 14,
	TEXATTRIBUTES_VAR = 15,
	TEXEMISSION_VAR = 16,
	TEXNORMALMAP_VAR = 17,
	ILIGHTCOUNT_VAR = 18,
	FGAMMA_VAR = 19,
	VECTIME_VAR = 20,
	VECFOGCOLOR_VAR = 21,
	IDEBUGMODE_VAR = 22,
	USEINSTANCING_VAR = 23,
	USEBONES_VAR = 24,
} SHADERVAR;

typedef enum STAGETYPE {
	ENTITY_STAGE,
	POSTPROCESSING_STAGE,
	CUSTOM_STAGE,
} STAGETYPE;

typedef enum TASKSTATE {
	TASK_DEAD,
	TASK_READY,
	TASK_SUSPENDED,
	TASK_DISABLED,
	TASK_RUNNING,
} TASKSTATE;


#endif // _ACKNEXT_ACKDEF_H_
