#ifndef _ACKNEXT_ACKENUM_H_
#define _ACKNEXT_ACKENUM_H_

typedef enum BUFFERTYPE {
	VERTEXBUFFER,
	INDEXBUFFER,
} BUFFERTYPE;

typedef enum ERROR {
	ERR_NOERROR,
	ERR_OUTOFMEMORY,
	ERR_INVALIDARGUMENT,
	ERR_INVALIDOPERATION,
	ERR_SDL,
} ERROR;

typedef enum FILETYPE {
	PHYSICAL_FILE,
	VIRTUAL_FILE,
} FILETYPE;

typedef enum LIGHTTYPE {
	AMBIENT_LIGHT,
	DIRECTIONAL_LIGHT,
	POINT_LIGHT,
	SPOT_LIGHT,
} LIGHTTYPE;

typedef enum PIXELFORMAT {
	FORMAT_RGB,
	FORMAT_RGBA,
	FORMAT_RGBA16F,
	FORMAT_RGBA32F,
} PIXELFORMAT;

typedef enum SHADERTYPE {
	VERTEXSHADER,
	INDEXSHADER,
	GEOMETRYSHADER,
	TESSCTRLSHADER,
	TESSEVALSHADER,
} SHADERTYPE;

typedef enum SHADERVAR {
	MATWORLD_VAR,
	MATVIEW_VAR,
	MATPROJ_VAR,
	MATWORLDVIEW_VAR,
	MATVIEWPROJ_VAR,
	MATWORLDVIEWPROJ_VAR,
	VECVIEWDIR_VAR,
	VECVIEWPOS_VAR,
	VECVIEWPORT_VAR,
	VECCOLOR_VAR,
	VECEMISSION_VAR,
	VECATTRIBUTES_VAR,
	TEXCOLOR_VAR,
	TEXATTRIBUTES_VAR,
	TEXEMISSION_VAR,
} SHADERVAR;

typedef enum STAGETYPE {
	ENTITY_STAGE,
	POSTPROCESSING_STAGE,
	CUSTOM_STAGE,
} STAGETYPE;


#endif // _ACKNEXT_ACKDEF_H_
