#ifndef _ACKNEXT_ACKVARS_H_
#define _ACKNEXT_ACKVARS_H_

#include "config.h"
#include "ackmath.h"

ACKVAR ACKCONST SIZE screen_size;
ACKVAR var screen_gamma;

ACKVAR EVENT * ACKCONST on_begin_frame; // Called before starting the update loop

// Time vars:

ACKVAR ACKCONST int total_frames;
ACKVAR ACKCONST var total_time;
ACKVAR ACKCONST var time_step;

// Color vars:
ACKVAR ACKCONST COLOR COLOR_BLACK;
ACKVAR ACKCONST COLOR COLOR_RED;
ACKVAR ACKCONST COLOR COLOR_GREEN;
ACKVAR ACKCONST COLOR COLOR_BLUE;
ACKVAR ACKCONST COLOR COLOR_YELLOW;
ACKVAR ACKCONST COLOR COLOR_MAGENTA;
ACKVAR ACKCONST COLOR COLOR_CYAN;
ACKVAR ACKCONST COLOR COLOR_WHITE;
ACKVAR ACKCONST COLOR COLOR_TRANSPARENT;

#endif // _ACKNEXT_ACKVARS_H_
