#ifndef _UNIFORM
#error _UNIFORM must be defined!
#endif

_UNIFORM(matWorld, GL_FLOAT_MAT4, MATWORLD_VAR, MATRIX)
_UNIFORM(matWorldView, GL_FLOAT_MAT4, MATWORLDVIEW_VAR, MATRIX)
_UNIFORM(matWorldViewProj, GL_FLOAT_MAT4, MATWORLDVIEWPROJ_VAR, MATRIX)
_UNIFORM(matView, GL_FLOAT_MAT4, MATVIEW_VAR, MATRIX)
_UNIFORM(matViewProj, GL_FLOAT_MAT4, MATVIEWPROJ_VAR, MATRIX)
_UNIFORM(matProj, GL_FLOAT_MAT4, MATPROJ_VAR, MATRIX)

_UNIFORM(vecViewPos, GL_FLOAT_VEC3, VECVIEWPOS_VAR, VECTOR)
_UNIFORM(vecViewDir, GL_FLOAT_VEC3, VECVIEWDIR_VAR, VECTOR)
_UNIFORM(vecViewPort, GL_FLOAT_VEC4, VECVIEWPORT_VAR, VECTOR)
_UNIFORM(fArc, GL_FLOAT, FARC_VAR, float)

_UNIFORM(vecAlbedo, GL_FLOAT_VEC4, VECALBEDO_VAR, COLOR)
_UNIFORM(vecEmission, GL_FLOAT_VEC4, VECEMISSION_VAR, COLOR)
_UNIFORM(vecAttributes, GL_FLOAT_VEC3, VECATTRIBUTES_VAR, VECTOR)

_UNIFORM(texColor, GL_SAMPLER_2D, TEXCOLOR_VAR, int)
_UNIFORM(texAttributes, GL_SAMPLER_2D, TEXATTRIBUTES_VAR, int)
_UNIFORM(texEmission, GL_SAMPLER_2D, TEXEMISSION_VAR, int)
_UNIFORM(texNormalMap, GL_SAMPLER_2D, TEXNORMALMAP_VAR, int)

_UNIFORM(fGamma, GL_FLOAT, FGAMMA_VAR, float)
_UNIFORM(vecTime, GL_FLOAT_VEC2, VECTIME_VAR, VECTOR2)

_UNIFORM(vecFogColor, GL_FLOAT_VEC4, VECFOGCOLOR_VAR, COLOR)

_UNIFORM(iLightCount, GL_INT, ILIGHTCOUNT_VAR, int)
_UNIFORM(iDebugMode, GL_INT, IDEBUGMODE_VAR, int)

_UNIFORM(useInstancing, GL_BOOL, USEINSTANCING_VAR, int)
_UNIFORM(useBones, GL_BOOL, USEBONES_VAR, int)

/*
UNIFORM(iLightType, GL_INT, ILIGHTTYPE_VAR)
UNIFORM(fLightIntensity, GL_FLOAT, FLIGHTINTENSITY_VAR)
UNIFORM(fLightArc, GL_FLOAT, FLIGHTARC_VAR)
UNIFORM(vecLightPos, GL_FLOAT_VEC3, VECLIGHTPOS_VAR)
UNIFORM(vecLightDir, GL_FLOAT_VEC3, VECLIGHTDIR_VAR)
UNIFORM(vecLightColor, GL_FLOAT_VEC3, VECLIGHTCOLOR_VAR)
*/
